#!/bin/bash

# This script demonstrates how to use the S3 presigned URL to upload content

# Replace this with the presigned URL generated by the application
PRESIGNED_URL="YOUR_PRESIGNED_URL_HERE"

# Replace this with the content type you specified when generating the URL
CONTENT_TYPE="text/plain"

# Example content to upload
CONTENT="This is some example content that will be uploaded to S3 using the presigned URL."

# Use curl to upload the content
curl -X PUT -H "Content-Type: $CONTENT_TYPE" --data-binary "$CONTENT" "$PRESIGNED_URL"

echo -e "\nUpload complete!"
